// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":false,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"BugFixWaterSurfaceLag","status":false,"description":"オートタイルのラグ修正プラグイン","parameters":{}},
{"name":"BMSP","status":false,"description":"BMSPベースプラグインです。","parameters":{}},
{"name":"SceneGlossary","status":false,"description":"Glossary Plugin","parameters":{"UseCategory":"OFF","CommandName":"Glossary","CommandName2":"","CommandName3":"","CommandName4":"","ItemType":"A","AutoAddition":"ON","FontSize":"22","GlossaryListWidth":"240","HelpText":"Select the Words","HelpText2":"Select the category","UsableItem":"OFF","AutoResizePicture":"ON","PicturePosition":"top","PictureAlign":"center","BackPicture":""}},
{"name":"K_MessageWindowAdjust","status":false,"description":"メッセージウィンドウ幅の調整をおこないます。","parameters":{}},
{"name":"K_OriginalMenuScreen","status":false,"description":"メニュー画面をオリジナルのものに変更します。","parameters":{"Add_LocationInfo":"1","Information_move":"選んだ場所へ瞬時に移動します。","Information_memo":"一度行ったマップ解説を読みます。","Information_item":"入手したアイテムを使用します。","Information_skill":"習得したスキルを使用します。","Information_equip":"装備を変更します。","Information_status":"ステータスを確認します。","Information_formation":"パーティの並び順を変更します。","Information_options":"オプション画面を開きます。","Information_save":"これまでのデータをセーブします。","Information_gameEnd":"ゲームを終了します。"}},
{"name":"OverpassTile","status":true,"description":"Settings for bridges which characters can pass through.","parameters":{"Overpass Region ID":"255","Gateway Region ID":"254"}},
{"name":"ParallaxesNonBlur","status":false,"description":"視差ゼロ遠景のぼかし除去プラグイン","parameters":{}},
{"name":"Foreground","status":true,"description":"display foreground tiling sprite","parameters":{}},
{"name":"YEP_PartySystem","status":true,"description":"v1.13 Replaces the default 'Formation' command with a new\r\nmenu for players to easily change party formations.","parameters":{"---General---":"","Max Battle Members":"4","Show Battle Command":"true","Enable Battle Command":"true","Battle Cooldown":"1","Maximum Followers":"4","EXP Distribution":"false","---Menu---":"","Help Window":"false","Text Alignment":"center","Change Command":"Change","Remove Command":"Remove","Revert Command":"Revert","Finish Command":"Finish","---Selection---":"","Empty Text":"- Empty -","Actor Face":"true","Actor Sprite":"true","---List---":"","Remove Icon":"16","Show Sprite":"true","Sprite Y Buffer":"16","In Party Text Color":"6","---Locking---":"","Lock First Actor":"true","Locked Icon":"195","Required Icon":"205","---Detail Window---":"","Enable Detail Window":"true","List Width":"300","Actor Parameters":"Parameters","Actor Equipment":"Equipment"}}
];
